# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  super-lint:
    name: Lint code base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env: 
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      # Runs a set of commands using the runners shell

  # You may pin to the exact commit or the version.
  # uses: cross-the-world/ssh-pipeline@7f022867934a210af826af99ef80d96f03a094d5
  uses: cross-the-world/ssh-pipeline@v1.2.0
  with:
    # ssh remote host
    host: w013af91.kasserver.com
    # ssh remote port
    port: # optional, default is 22
    # ssh remote user
    user: ssh-w01be28d
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa
    key: AAACAQCq5xYRzhia3sUNcUxD8x9EZSyuWDQQirHHJBRxO/+qfBxAL7Su1uaTGNe/
          cKMJC8dEwLBzQd8515aw/chI8/pi2+aUiDpixxD2ve+gT4XCqwadfbtOaX3L9Zs8
          6W+hTWU8TSQCyw3Vt7CXSkFdMohykPXPX7Gxo239+aWrnkE2iP4GPlIgKUYffk3M
          U+KPFi7P5CkiTcosWqXuUUgEPxmw7C3S9HjUPFNoQVCevchRMYiI9jWq1abYKI1U
          LN66zPznkqtD/pg5YzSYrWdND4xF2oDYGFC1qhq8HePrYrUIf+cOraahiAPI32Yw
          zbVnrxNekxsoLn+VBgLqRoce27U3ZZXwD//8lHeZGchLvuwWrJ121YXSO8V4eTps
          V8YRm/MSks2ak7loJldiRpPg0NJ/jT+1VdNTH8llYYghdsVoFU/Vn6wd317eyOK1
          QBg7G/9aXz+zXrTYkV52VbSaxY8cmJ8c1UFh35Xv5kqqQtBHv2FhViFt6gVCMR7M
          ZKRbek1kbcJ8Mq2Zy/T8qTMBW7brBUNI1ki8o9UtNonMqBtJnGJtwnB+miTjFtAO
          obGabTtIaGM9QSCfyJvCKGQi5FNZpaHc8G0xYvPukwFvIVmsRkwEEeriVv8dBTWc
          r7eBYvJkWXAxoEkmh+hmV6Rn3+LLMTZshZzXWA0csL9kVCBLNQAAAQEA6AwvWyA8
          /0vE1TmqzI0Rvt6VSp7Po+2zxuLMnsoaQ97VzHRmjokH59N3NaYvwavaUF9A5Toz
          O1fE9JiSCu6cHOnWb59zIaJYfkfC0Se9HuQm9GaTNYte/ZQ2Tq5n2A04wF7c83YP
          9UpK5Wj+Z7b4OykHnYiitCCJAQxFkGZuTYEpuCyRqrxt5cu/gh4FKc5wYusooYje
          /F9Dc2gTVbZdTHPUsINY7sBBYksrXnPc/sQ9LNwJClYWfPw7hD6uyv2P5KlbD95V
          OUEFcdStszuYtrC78m2X06Q7zxpXuD0XUubzWMpEH6U+zcf8P6pJBXc2yiV7Do+o
          IGufz+8BxJVLawAAAQEAzS4GYqoM/4EDgGeiCD9TS9YuSQRp9OLM+PoKOzARx+jD
          8i0YU/4/R95/ObpY89bVNIl452WKXPh2mzlRlQTyo3TInsSzPVJTyoxDEGqJRGs/
          xVnt4Y7I6DIL6u+JTpdReqDI4coKou1ex9+GHVAyYf5P0JvMeGsO6su9Z6AXJhZ+
          jGNaEFl+ZugWfNZjFezCwl1kIPp5RFEmf8EN3YHr0XJlrdTYXFe2x5EkEzpK7p5p
          PWB9cy9dgORXsgSVrbEYD2F5tZvsFoSdI3BpTE8RJJgr/U7gxY5zch7c5SJXrbv7
          rngXj/KirB7h1QWplfL7PMdkQP7xVoWpqOrsoHZRIwAAAQAV3dCHn/Vi1die4tQY
          IN81LCcN5BwXXdkYM/5CwoJzTZWcdH1R8nAXZz6ZMCwsHw/VjkBBPUfdqQuf/ypt
          kNSSHFQ/9VZlyN1HZch8AgJfoeAoevt9PeFZbIjTY657vmPwJKgQzZWjzsSG26HC
          1ARsEHLCG7Rjykbzdc8x6wvMEpdb5nxtiXnYtKaczG+SnlajeI4E6bW8aTPNsIkc
          94B/tFaXF5SX3xvasorPQi27kDPiw6jZ/4veQjjmkJL52QD5ja8ux50bT6BuGMra
          Uvhs8MukIafCNegyJZcW1blQ3c1uy80EpR8h4Hx+sZ3xAkzRHoNDDceVmpckQmOE
          q8BA
    # ssh remote password
    pass: eYpddzoN5wtefN9B
    # connection timeout to remote host
    connect_timeout: # optional, default is 30s
    # execute commands on ssh
    script: # optional
